
pool:
  name: eryph


jobs:
- job: Init
  steps:
    - task: PowerShell@2
      displayName: setup tools
      inputs:
        filePath: './prepare.ps1'
        arguments: '$(UserMail) $(InvitationCode)'
        warningPreference: 'continue'
        informationPreference: 'continue'
        verbosePreference: 'continue'
    - task: CmdLine@2
      displayName: clone basecatlet repo
      inputs:
        script: 'git clone https://github.com/eryph-org/basecatlets-hyperv.git'

- job: build
  dependsOn: Init
  strategy:
    maxParallel: 1
    matrix: 
      ubuntu-20.04: 
        template: ubuntu-20.04
  steps:
  - task: PowerShell@2
    inputs:
      filePath: './build.ps1'
      arguments: '-Filter $(template) -BuildPath basecatlets-hyperv\builds'