resources:
  repositories:
  - repository: basecatlets # The name used to reference this repository in the checkout step
    type: github
    endpoint: eryph-org
    name: eryph-org/basecatlets-hyperv


pool:
  name: eryph


jobs:
- job: Init
  steps:
    - task: PowerShell@2
      displayName: setup tools
      inputs:
        filePath: './prepare.ps1'
        arguments: '$(UserMail) $(InvitationCode)'
        warningPreference: 'continue'
        informationPreference: 'continue'
        verbosePreference: 'continue'

- job: build
  dependsOn: Init
  timeoutInMinutes: 120
  strategy:
    maxParallel: 1
    matrix: 
      ubuntu-20.04: 
        template: ubuntu-20.04
      ubuntu-22.04: 
        template: ubuntu-22.04        
      winsrv2022-standard: 
        template: winsrv2022-standard
  steps:
  - checkout: self
  - checkout: basecatlets
    clean: true

  - task: CmdLine@2
    inputs:
      script: 'mkdir $(Build.SourcesDirectory)\basecatlets-hyperv\builds'
    
  - task: PowerShell@2
    inputs:
      filePath: '.\eryph-genes\build.ps1'
      arguments: '-Filter $(template) -BuildPath $(Build.SourcesDirectory)\basecatlets-hyperv\builds'      