
pool:
  name: eryph

jobs:
 - job: Init
   steps:
     - task: PowerShell@2
       inputs:
         filePath: './prepare.ps1'
         arguments: '$(UserMail) $(InvitationCode)'
     - task: CmdLine@2
       inputs:
         script: 'git clone https://github.com/eryph-org/basecatlets-hyperv.git'