resources:
  repositories:
  - repository: basecatlets # The name used to reference this repository in the checkout step
    type: github
    endpoint: eryph-org
    name: eryph-org/basecatlets-hyperv


pool:
  name: eryph

jobs:
- job: winbuild
  timeoutInMinutes: 240
  strategy:
    maxParallel: 1
    matrix:        
      winsrv2022-standard: 
        template: winsrv2022-standard    
  steps:
  - checkout: self
  - checkout: basecatlets
    clean: true

  - task: Pre-PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'iex "& { $(irm https://raw.githubusercontent.com/dbosoft/eryph-genes/refs/heads/main/prepare.ps1) } ${env:USERMAIL} ${env:INVITATIONCODE}"'
      warningPreference: 'continue'
      informationPreference: 'continue'
      verbosePreference: 'continue'
  - task: CmdLine@2
    inputs:
      script: 'mkdir $(Build.SourcesDirectory)\basecatlets-hyperv\builds'
    
  - task: PowerShell@2
    inputs:
      filePath: '.\eryph-genes\build.ps1'
      arguments: '-Filter $(template) -BuildPath $(Build.SourcesDirectory)\basecatlets-hyperv\builds'      